### ISSUE TITLE
Hole size is 180x180?

### ISSUE THREAD

**Issue by jkschin** [leehomyc/Faster-High-Res-Neural-Inpainting#23]
Your paper mentioned that the holes for a 512x512 image are 256x256. However, the demo in this repository has hole sizes of 180x180. Is there a version where the holes are 256x256?

**Comment by leehomyc** [comment]
Hi I dont think the hole size is 180x180 but I need to look at what the actual size is. It is definitely smaller than 256x256 because we need to have an overlapping part for the content network, and also for the final result we need to blend it to make it look better. If you want the hole to be 256x256, I think its doable by training another content network that predict hole larger than 256x256 and then follow the same procedure to overlap and blend.

Make sense?

**Comment by leehomyc** [comment]
If you look at the original Context Encoder paper where we borrow the content network from their hole size is actually 56x56 (given an image of 128x128) because they need to overlap the border and give larger weight to that border region so that the inpainting result is consistent.

**Comment by jkschin** [comment]
Thanks for clarification! :+1:
